### ISSUE TITLE
Bot link not working

### ISSUE THREAD

**Issue by Kellett** [RtiM0/telegram-mirror-bot#1]
Bot isn't formatting the github link correctly. Looks like there is an extra space at the end

![image](https://user-images.githubusercontent.com/1553850/198278194-dfd1ed67-c055-4047-8031-b3b146e11373.png)

**Comment by RtiM0** [comment]
Merged.
Thanks for bringing this to my attention, Reddit's RTF is inconsistent across different pages which made me miss it!
